<Project>
  <PropertyGroup>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageVersion Include="MSTest" Version="4.3.3" />
    <PackageVersion Include="SSH.NET" Version="2025.1.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageVersion Include="Webprofusion.Certify.ACME.Anvil" Version="3.3.3" />
  </ItemGroup>
</Project>
